// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerceMvc.Context;

#nullable disable

namespace eCommerceMvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413135358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eCommerceMvc.Models.PageContentEntities.ContentBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImagesId")
                        .HasColumnType("int");

                    b.Property<int>("PageContentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImagesId");

                    b.HasIndex("PageContentId");

                    b.ToTable("contentBases");
                });

            modelBuilder.Entity("eCommerceMvc.Models.PageContentEntities.Images", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("images");
                });

            modelBuilder.Entity("eCommerceMvc.Models.PageContentEntities.PageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("pages");
                });

            modelBuilder.Entity("eCommerceMvc.Models.PageContentEntities.Symbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("symbols");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Shopify.ShopifyApiInfo", b =>
                {
                    b.Property<string>("ShopDomain")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanCreateProducts")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReadProducts")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ShopDomain");

                    b.ToTable("shopifyApiInfos");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Shopify.ShopifyProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ShopifyProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("shopifyProducts");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Shopify.ShopifyProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<long>("ShopifyImageId")
                        .HasColumnType("bigint");

                    b.Property<int>("ShopifyProductId")
                        .HasColumnType("int");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShopifyProductId");

                    b.ToTable("shopifyProductImages");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Shopify.ShopifyProductOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<long>("ShopifyOptionId")
                        .HasColumnType("bigint");

                    b.Property<int>("ShopifyProductId")
                        .HasColumnType("int");

                    b.Property<string>("ValuesCsv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShopifyProductId");

                    b.ToTable("shopifyProductOptions");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Shopify.ShopifyVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InventoryManagement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryPolicy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShopifyProductId")
                        .HasColumnType("int");

                    b.Property<long>("ShopifyVariantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Taxable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShopifyProductId");

                    b.ToTable("shopifyVariants");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Trendyol.TrendyolApiInfo", b =>
                {
                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanCreateProducts")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReadProducts")
                        .HasColumnType("bit");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<string>("IntegratorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionBaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageAuthorizedIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageBaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StageIpAuthorized")
                        .HasColumnType("bit");

                    b.HasKey("SellerId");

                    b.ToTable("trendyolApiInfos");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Trendyol.TrendyolBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrendyolBrandId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("trendyolBrands");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Trendyol.TrendyolCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrendyolCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("trendyolCategories");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Trendyol.TrendyolProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductMainId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StockCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrendyolBrandId")
                        .HasColumnType("int");

                    b.Property<int>("TrendyolCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("VatRate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrendyolBrandId");

                    b.HasIndex("TrendyolCategoryId");

                    b.ToTable("trendyolProducts");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Trendyol.TrendyolProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AttributeValueId")
                        .HasColumnType("bigint");

                    b.Property<int>("TrendyolProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrendyolProductId");

                    b.ToTable("trendyolProductAttributes");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Trendyol.TrendyolProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TrendyolProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TrendyolProductId");

                    b.ToTable("trendyolProductImages");
                });

            modelBuilder.Entity("eCommerceMvc.Models.PageContentEntities.ContentBase", b =>
                {
                    b.HasOne("eCommerceMvc.Models.PageContentEntities.Images", "Images")
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerceMvc.Models.PageContentEntities.PageContent", "PageContent")
                        .WithMany("ContentBases")
                        .HasForeignKey("PageContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Images");

                    b.Navigation("PageContent");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Shopify.ShopifyProductImage", b =>
                {
                    b.HasOne("eCommerceMvc.Models.Shopify.ShopifyProduct", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ShopifyProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Shopify.ShopifyProductOption", b =>
                {
                    b.HasOne("eCommerceMvc.Models.Shopify.ShopifyProduct", "Product")
                        .WithMany("Options")
                        .HasForeignKey("ShopifyProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Shopify.ShopifyVariant", b =>
                {
                    b.HasOne("eCommerceMvc.Models.Shopify.ShopifyProduct", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ShopifyProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Trendyol.TrendyolProduct", b =>
                {
                    b.HasOne("eCommerceMvc.Models.Trendyol.TrendyolBrand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("TrendyolBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerceMvc.Models.Trendyol.TrendyolCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("TrendyolCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Trendyol.TrendyolProductAttribute", b =>
                {
                    b.HasOne("eCommerceMvc.Models.Trendyol.TrendyolProduct", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("TrendyolProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Trendyol.TrendyolProductImage", b =>
                {
                    b.HasOne("eCommerceMvc.Models.Trendyol.TrendyolProduct", "Product")
                        .WithMany("Images")
                        .HasForeignKey("TrendyolProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerceMvc.Models.PageContentEntities.PageContent", b =>
                {
                    b.Navigation("ContentBases");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Shopify.ShopifyProduct", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Options");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Trendyol.TrendyolBrand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Trendyol.TrendyolCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eCommerceMvc.Models.Trendyol.TrendyolProduct", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
